apiVersion: v1
kind: ConfigMap
metadata:
    name: fluent-bit-config
    namespace: nextjs
data:
    fluent-bit.conf: |
        [SERVICE]
            Flush         1
            Log_Level     info
            Daemon        off
            Parsers_File  parsers.conf
            HTTP_Server   On
            HTTP_Listen   0.0.0.0
            HTTP_Port     2020

        [INPUT]
            Name              tail
            Path              /var/log/containers/*nextjs*.log
            Parser            docker
            Tag               kube.*
            Refresh_Interval  5
            Mem_Buf_Limit     50MB
            Skip_Long_Lines   On

        [OUTPUT]
            Name  stdout
            Match *
