apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nextjs-ingress
    namespace: nextjs-app
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
    tls:
        - hosts:
              - your-domain.com
          secretName: nextjs-tls
    rules:
        - host: your-domain.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: nextjs-service
                            port:
                                number: 80
