apiVersion: v1
kind: Service
metadata:
    name: nextjs-service
    namespace: nextjs-app
spec:
    type: ClusterIP
    ports:
        - port: 80
          targetPort: 3000
    selector:
        app: nextjs-app
